#include "project.hpp"

#include <cctype>
#include <fstream>
#include <sstream>

#include "except.hpp"
#include "unicode.hpp"
#include "lockfile.hpp"
#include "log.hpp"
#include "process.hpp"

namespace fs = std::filesystem;

namespace nsmb {

namespace {

constexpr std::string_view ENV_NAME = ".ncpatcher.env";

const char* const PROJECT_FILES[] = { "ncpatcher.yaml", "ncpatcher.yml", "ncpatcher.json" };

// The value as NCPatcher's own .env reader will see it. That reader trims and
// then strips one layer of matching quotes, so a value with edge whitespace has
// to be quoted to survive -- and a value that is already quote-wrapped would be
// unwrapped, which no real path is, but which is worth not producing.
std::string envValue(const std::string& value)
{
	const bool padded = !value.empty()
		&& (std::isspace(static_cast<unsigned char>(value.front()))
			|| std::isspace(static_cast<unsigned char>(value.back())));
	const bool quoted = value.size() >= 2 && value.front() == value.back()
		&& (value.front() == '"' || value.front() == '\'');

	if (!padded && !quoted)
		return value;
	if (value.find('"') == std::string::npos)
		return "\"" + value + "\"";
	if (value.find('\'') == std::string::npos)
		return "'" + value + "'";

	throw nsmb::exception("The reference path contains both kinds of quote and cannot be written "
	                    "to " + std::string(ENV_NAME) + ": " + value);
}

std::string readFile(const fs::path& file)
{
	std::ifstream stream(file, std::ios::binary);
	if (!stream.is_open())
		return {};

	std::ostringstream buffer;
	buffer << stream.rdbuf();
	return buffer.str();
}

} // namespace

fs::path Project::lockPath() const
{
	return root / Lockfile::NAME;
}

fs::path Project::envPath() const
{
	return root / ENV_NAME;
}

Project findProject(const fs::path& start)
{
	std::error_code error;
	fs::path directory = fs::absolute(start, error);
	if (error)
		directory = start;
	directory = directory.lexically_normal();

	for (fs::path at = directory; ; at = at.parent_path())
	{
		if (fs::is_regular_file(at / Lockfile::NAME, error))
			return Project{ at, true };
		if (!at.has_relative_path())
			break;
	}

	for (fs::path at = directory; ; at = at.parent_path())
	{
		for (const char* name : PROJECT_FILES)
		{
			if (fs::is_regular_file(at / name, error))
				return Project{ at, false };
		}
		if (!at.has_relative_path())
			break;
	}

	return Project{ directory, false };
}

bool writeEnvFile(const fs::path& file, const fs::path& referenceRoot,
	const std::string& repo, const std::string& rev)
{
	std::ostringstream out;
	out << "# Generated by nsmbtool. Do not edit, and do not commit.\n"
	    << "#\n"
	    << "# Every value here comes from " << Lockfile::NAME << "; run\n"
	    << "#     nsmbtool reference sync\n"
	    << "# after changing it. NCPatcher reads this before ${env.*} resolves, and what is\n"
	    << "# here overrides the ambient environment -- which is the point: a global\n"
	    << "# NSMBREF_ROOT in a shell profile must not decide what this project builds\n"
	    << "# against.\n"
	    << "#\n"
	    << "# Machine-specific variables do not belong here and would be dropped on the next\n"
	    << "# sync. NSMB_NITRO_ROOT in particular stays in the shell profile: those headers\n"
	    << "# are private, cannot be fetched, and are a property of the machine.\n"
	    << "#\n"
	    << "#   reference " << repo << "\n"
	    << "#   revision  " << rev << "\n"
	    << "\n"
	    << "NSMBREF_ROOT=" << envValue(pathToUtf8Generic(referenceRoot)) << "\n";

	const std::string text = out.str();
	if (readFile(file) == text)
		return false;

	std::ofstream stream(file, std::ios::binary | std::ios::trunc);
	if (!stream.is_open())
		throw nsmb::exception("Could not write " + pathToUtf8Generic(file) + ".");
	stream.write(text.data(), std::streamsize(text.size()));
	if (!stream)
		throw nsmb::exception("Could not write " + pathToUtf8Generic(file) + ".");

	return true;
}

EnvFileStanding envFileStanding(const fs::path& projectRoot)
{
	// Asked of git rather than parsed out of .gitignore: the rule may live in a
	// parent directory, in .git/info/exclude, or in the user's global ignore
	// file, and only git knows about all three. A directory that is not a
	// repository has nothing to commit the file to, so it counts as covered.
	const ProcessResult inside = run({ "git", "rev-parse", "--is-inside-work-tree" }, projectRoot);
	if (!inside.ok())
		return EnvFileStanding::Ignored;

	// Tracked first, and it is the case worth separating: check-ignore says
	// nothing is ignored about a file already in the index, which reads as "not
	// ignored" when the real answer is "ignoring it will not help any more".
	if (run({ "git", "ls-files", "--error-unmatch", "--", std::string(ENV_NAME) }, projectRoot).ok())
		return EnvFileStanding::Tracked;

	if (run({ "git", "check-ignore", "--quiet", std::string(ENV_NAME) }, projectRoot).ok())
		return EnvFileStanding::Ignored;

	return EnvFileStanding::Uncovered;
}

} // namespace nsmb
